# Generated by Django 3.2.8 on 2021-10-20 06:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BLACKBERRY', 'Ежевика'), ('RASPBERRY', 'Малина'), ('BLUEBERRY', 'Голубика'), ('STRAWBERRY', 'Клубника')], max_length=30)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PISTACHIO', 'Фисташки'), ('MERINGUE', 'Безе'), ('HAZELNUTS', 'Фундук'), ('PECAN', 'Пекан'), ('MARSHMALLOW', 'Маршмеллоу'), ('MARZIPAN', 'Марципан')], max_length=30)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1L', '1 уровень'), ('2L', '2 уровня'), ('3L', 'З уровня')], max_length=10)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU')),
                ('street', models.CharField(blank=True, max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=20)),
                ('flat_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SQUARE', 'Квадрат'), ('CIRCLE', 'Круг'), ('RECTANGLE', 'Прямоугольник')], max_length=30)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ZERO', 'Без топпинга'), ('WHITE', 'Белый соус'), ('CARAMEL', 'Карамельный сироп'), ('MAPLE', 'Кленовый сироп'), ('STRAWBERRY', 'Клубничный сироп'), ('BLUEBERRY', 'Черничный сироп'), ('MILK', 'Молочный шоколад')], max_length=30)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('START', 'Заказ создан'), ('CANCELED', 'Заказ отменен'), ('PROCESSING', 'Заказ обрабатывается'), ('MANUFACTURING', 'Готовим ваш торт'), ('DELIVERING', 'Торт в пути'), ('DONE', 'Торт у вас')], default='START', max_length=30)),
                ('promo', models.CharField(blank=True, max_length=15)),
                ('comment', models.TextField(blank=True)),
                ('delivery_date', models.DateTimeField(default=datetime.datetime(2021, 10, 23, 6, 42, 27, 511035, tzinfo=utc))),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='cake.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('berry', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='berry', to='cake.berry')),
                ('decor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='decor', to='cake.decor')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='cake.level')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.order')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shape', to='cake.level')),
                ('title', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='decor', to='cake.title')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping', to='cake.topping')),
            ],
        ),
    ]
