# Generated by Django 3.2.8 on 2021-10-21 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_auto_20211021_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shape', to='cake.shape'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 11, 31, 26, 432418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
