# Generated by Django 3.2.8 on 2021-10-21 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_auto_20211021_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='berry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berry', to='cake.berry'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decor', to='cake.decor'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decor', to='cake.title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 12, 2, 3, 593940, tzinfo=utc)),
        ),
    ]
